spring.application.name=springcrud

# collegamento db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/crudspring
spring.datasource.username=root
spring.datasource.password=Root

# Mostra query in console
# udate solo in sviluppo al primo avvio crea tabelle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Abilita i metodi delete update con hidden input
spring.mvc.hiddenmethod.filter.enabled=true

# Start data sql not at first alunch when creating db
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# set credenziali security
# spring.security.user.name=admin
# spring.security.user.password=admin